services:
    mkdocs:
        container_name: server-mkdocs
        build: .
        ports:
            - "8888:8888"
        networks:
            - inside-server

        restart: unless-stopped

networks:
  inside-server:
    external: true
