services:
    mkdocs:
        container_name: server-mkdocs
        build: .
        ports:
            - "8888:8888"

        restart: unless-stopped
        networks:
            - inside-server

networks:
    inside-server:
        external: true
