services:
    mkdocs:
        container_name: server-mkdocs
        build: .
        ports:
            - "8888:8888"
        networks:
        - inside-server

networks:
  inside-server:
    external: true